#!/usr/bin/env bash
#
# Regenerate the cross-version wire fixtures in
# crates/termland-protocol/tests/fixtures/.
#
# For each released tag this checks out a worktree, builds *that version's*
# termland-protocol, and has it serialise a handful of messages. The bytes
# committed under tests/fixtures/<tag>/ are therefore what that release
# actually put on the wire — not a reconstruction of it.
#
# That distinction is the point. The hand-written "old peer" structs in
# messages.rs prove how serde behaves, but they are a guess at what old code
# sent; if the guess is wrong, the test passes while real interop breaks.
# These fixtures cannot be wrong about it.
#
# Only termland-protocol is built, never the workspace: that crate has no
# FFmpeg dependency at any released tag, so old versions still compile today
# even though their server and client would not — the libavutil soname has
# moved on since, which is why a v0.5-era binary no longer runs at all.
#
# Run after cutting a release, to capture the new version:
#     ./packaging/gen-protocol-fixtures.sh
#
set -euo pipefail

cd "$(dirname "$0")/.."
REPO=$(pwd)
FIXTURES="$REPO/crates/termland-protocol/tests/fixtures"
WORK=$(mktemp -d)
trap 'git worktree remove --force "$WORK/wt" 2>/dev/null || true; rm -rf "$WORK"; git worktree prune' EXIT

# The protocol grew in four observable steps. Rather than hardcode which tag
# is which, ask each version's own source what it supports — so a tag added
# later needs no change here.
emit_source() {
  local src=$1 has_codecs=$2 has_sessionlist=$3 has_audio=$4

  cat <<'RS'
//! Generated by packaging/gen-protocol-fixtures.sh — do not edit in place.
use termland_protocol::*;

fn main() {
    let out = std::env::args().nth(1).expect("usage: emit_fixtures <dir>");
    std::fs::create_dir_all(&out).unwrap();
    let mut msgs: Vec<(&str, Message)> = vec![
        ("hello", Message::Hello(Hello {
            protocol_version: PROTOCOL_VERSION,
            client_name: "termland-client".into(),
        })),
RS

  # SessionCreate: the field set depends on the version.
  echo '        ("session_create", Message::SessionCreate(SessionCreate {'
  echo '            mode: SessionMode::Desktop, width: 1920, height: 1080, audio: true,'
  echo '            quality: 75, desktop_shell: None, encoder_preset: None,'
  echo '            encoder_crf: None, encoder_extra_params: None,'
  [ "$has_codecs" = y ]     && echo '            supported_codecs: VideoCodec::all_preferred(),'
  [ "$has_audio" = y ]      && echo '            supported_audio_codecs: AudioCodec::all_preferred(),'
  echo '        })),'

  echo '    ];'

  # Session listing arrived with persistent sessions in v0.5.0.
  if [ "$has_sessionlist" = y ]; then
    echo '    msgs.push(("session_list", Message::SessionList(SessionList {})));'
  fi

  cat <<'RS'
    for (name, m) in msgs {
        let bytes = m.encode().expect("encode");
        std::fs::write(format!("{out}/{name}.cbor"), &bytes).unwrap();
    }
    println!("  wrote {} fixtures", std::fs::read_dir(&out).unwrap().count());
}
RS
}

for tag in $(git tag | sort -V); do
  src=$(git show "$tag:crates/termland-protocol/src/messages.rs" 2>/dev/null) || {
    echo "  SKIP $tag (no protocol crate)"; continue; }

  has_codecs=n;      grep -q "supported_codecs"       <<<"$src" && has_codecs=y
  has_audio=n;       grep -q "supported_audio_codecs" <<<"$src" && has_audio=y
  has_sessionlist=n; grep -q "pub struct SessionList" <<<"$src" && has_sessionlist=y

  echo "=== $tag (codecs=$has_codecs sessions=$has_sessionlist audio=$has_audio) ==="
  git worktree remove --force "$WORK/wt" 2>/dev/null || true
  git worktree add -q --detach "$WORK/wt" "$tag"
  mkdir -p "$WORK/wt/crates/termland-protocol/examples"
  emit_source "$src" "$has_codecs" "$has_sessionlist" "$has_audio" \
    > "$WORK/wt/crates/termland-protocol/examples/emit_fixtures.rs"

  ( cd "$WORK/wt" && cargo run -q -p termland-protocol --example emit_fixtures -- \
      "$FIXTURES/$tag" ) || echo "  SKIPPED: $tag did not build"
done

echo
echo "Fixtures under $FIXTURES:"
find "$FIXTURES" -name '*.cbor' | sort | sed 's|.*/fixtures/|  |'
